server:
  port: 8178

spring:
  datasource:
    username: ghost
    password: ghost
    url:  jdbc:mysql://47.101.185.244:3306/docker-test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #连接池内最小空闲连接数
      minimum-idle: 5
      #连接池允许的最大连接数
      maximum-pool-size: 50
      #等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
  application:
    name: provider    #当前服务在注册中心的名称

  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev


eureka:
  client:
    service-url:
      defaultZone: http://eureka8176.com:8176/eureka/,http://eureka8177.com:8177/eureka/  #注册中心的地址
  instance:
      prefer-ip-address: true   #是否在注册中心的访问路径显示IP
      instance-id: payServer8178
      #客户端向Eureka发送心跳的时间间隔  s
      lease-renewal-interval-in-seconds: 3
      #Eureka服务端在收到最后一次心跳等待时间的上限，单位为秒（默认90秒），超时删除服务
      lease-expiration-duration-in-seconds: 5
mybatis:
  mapper-locations: mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"