server:
  port: 8179

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://192.168.5.128:3306/docker-test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: ghost
    password: ghost
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #连接池内最小空闲连接数
      minimum-idle: 5
      #连接池内最大连接数
      maximum-pool-size: 50
      #等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
  application:
    name: provider
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka8176.com:8176/eureka/,http://eureka8177.com:8177/eureka/   #注册中心的地址
  instance:
    prefer-ip-address: true
    instance-id: payServer8179
mybatis:
  mapper-locations: mapper/*.xml