spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hand_stu
    username: root
    password: cyf13209202523
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mapper/*.xml